ALTER TABLE item ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE inventory DROP COLUMN IF EXISTS total_quantity;

DROP TABLE IF EXISTS order_item;

DROP TABLE IF EXISTS orders;